service: corona-supplies

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: { Fn::GetAtt: [SuppliesDynamoDB, Arn] }

functions:
  scrape:
    handler: lambdas/scrape.handler
    events:
      - http: GET /scrape
  api:
    handler: lambdas/api.get
    events:
      - http: GET /api

resources:
  Resources:
    SuppliesDynamoDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'coronasupplies'
        AttributeDefinitions:
          - AttributeName: 'ProductType'
            AttributeType: 'S'
          - AttributeName: 'StoreNo#ProductID'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'ProductType'
            KeyType: HASH
          - AttributeName: 'StoreNo#ProductID'
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline
